// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '9167af2d-c13e-4d34-9a57-8f37dba6ff31',
    name: 'Subscription-1',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policydefinitions/testPolicyDefinition?api-version=2015-10-01-preview', '*')
  .reply(201, "{\"properties\":{\"displayName\":\"myPolicy\",\"policyType\":\"Custom\",\"policyRule\":{\"if\":{\"source\":\"action\",\"equals\":\"Microsoft.Storage/storageAccounts/write\"},\"then\":{\"effect\":\"deny\"}}},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/testPolicyDefinition\",\"type\":\"Microsoft.Authorization/policyDefinitions\",\"name\":\"testPolicyDefinition\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '392',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'westus:72c56ab1-49f1-4a34-8c47-e7eced424770',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': '22ff97ed-080d-4251-bd01-53435d7e7c7d',
  'x-ms-routing-request-id': 'WESTUS:20160408T210709Z:22ff97ed-080d-4251-bd01-53435d7e7c7d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourcegroups/testGroup?api-version=2016-02-01')
  .reply(200, "{\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup\",\"name\":\"testGroup\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-request-id': 'b3b4aa40-16a5-4ca1-b571-6e0215f9bc65',
  'x-ms-correlation-request-id': 'b3b4aa40-16a5-4ca1-b571-6e0215f9bc65',
  'x-ms-routing-request-id': 'WESTUS:20160408T210711Z:b3b4aa40-16a5-4ca1-b571-6e0215f9bc65',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:10 GMT',
  'content-length': '181' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.patch('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourcegroups/testGroup?api-version=2016-02-01', '*')
  .reply(200, "{\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup\",\"name\":\"testGroup\",\"location\":\"westus\",\"tags\":{},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '181',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-request-id': 'eed74794-fec8-422e-b36a-220985abe85e',
  'x-ms-correlation-request-id': 'eed74794-fec8-422e-b36a-220985abe85e',
  'x-ms-routing-request-id': 'WESTUS:20160408T210710Z:eed74794-fec8-422e-b36a-220985abe85e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyassignments/testPolicyAssignment?api-version=2015-10-01-preview', '*')
  .reply(201, "{\"properties\":{\"policyDefinitionId\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/testPolicyDefinition\",\"scope\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup\"},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyAssignments/testPolicyAssignment\",\"type\":\"Microsoft.Authorization/policyAssignments\",\"name\":\"testPolicyAssignment\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '489',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'westus:ead26f25-5628-41d9-bb39-f22e6ed84678',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '0ceb3ced-7fb5-42c2-b08c-d9e394bf04a7',
  'x-ms-routing-request-id': 'WESTUS:20160408T210711Z:0ceb3ced-7fb5-42c2-b08c-d9e394bf04a7',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyassignments/testPolicyAssignment?api-version=2015-10-01-preview')
  .reply(200, "{\"properties\":{\"policyDefinitionId\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/testPolicyDefinition\",\"scope\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup\"},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyAssignments/testPolicyAssignment\",\"type\":\"Microsoft.Authorization/policyAssignments\",\"name\":\"testPolicyAssignment\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '489',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  'x-ms-request-id': 'westus:29e6a9d4-f61e-4c92-85e5-5f8b225d6406',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '1b5da1e7-e30c-43de-b55f-0eebb4f798f2',
  'x-ms-routing-request-id': 'WESTUS:20160408T210711Z:1b5da1e7-e30c-43de-b55f-0eebb4f798f2',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyassignments?api-version=2015-10-01-preview')
  .reply(200, "{\"value\":[{\"properties\":{\"policyDefinitionId\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/testPolicyDefinition\",\"scope\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup\"},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyAssignments/testPolicyAssignment\",\"type\":\"Microsoft.Authorization/policyAssignments\",\"name\":\"testPolicyAssignment\"},{\"properties\":{\"displayName\":\"testVivekPA\",\"policyDefinitionId\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/testVivekNewPolicy\",\"scope\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/vtest\"},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/vtest/providers/Microsoft.Authorization/policyAssignments/testAssignment\",\"type\":\"Microsoft.Authorization/policyAssignments\",\"name\":\"testAssignment\"},{\"properties\":{\"policyDefinitionId\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/CostCenterTagPolicy\",\"scope\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/policies\"},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/policies/providers/Microsoft.Authorization/policyAssignments/CostCenterTagPolicyAssignment\",\"type\":\"Microsoft.Authorization/policyAssignments\",\"name\":\"CostCenterTagPolicyAssignment\"}]}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1502',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  'x-ms-request-id': 'westus:2183751b-02be-4688-bb5a-8caca39296ff',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'f0dd4eeb-fb27-48d1-b31b-6f0126f3a1ac',
  'x-ms-routing-request-id': 'WESTUS:20160408T210712Z:f0dd4eeb-fb27-48d1-b31b-6f0126f3a1ac',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyassignments/testPolicyAssignment?api-version=2015-10-01-preview')
  .reply(200, "{\"properties\":{\"policyDefinitionId\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/providers/Microsoft.Authorization/policyDefinitions/testPolicyDefinition\",\"scope\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup\"},\"id\":\"/subscriptions/9167af2d-c13e-4d34-9a57-8f37dba6ff31/resourceGroups/testGroup/providers/Microsoft.Authorization/policyAssignments/testPolicyAssignment\",\"type\":\"Microsoft.Authorization/policyAssignments\",\"name\":\"testPolicyAssignment\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '489',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  vary: 'Accept-Encoding',
  'x-ms-request-id': 'westus:157301b5-bbe3-4b4b-b3b0-c094a69ebf2a',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '84de3c90-64dd-47ac-9cac-4929a401873b',
  'x-ms-routing-request-id': 'WESTUS:20160408T210712Z:84de3c90-64dd-47ac-9cac-4929a401873b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 08 Apr 2016 21:07:12 GMT' });
 return result; }]];